export const imagePath = {
  eyeClose: require('../assests/images/eyeclose.png'),
  eyeOpen: require('../assests/images/eyeopen.png'),
  arrow: require('../assests/images/arrow.png'),
  Facebook: require('../assests/images/facebook.png'),
  Google: require('../assests/images/google.png'),
  success: require('../assests/images/success.png'),
  googleIcon: require('../assests/images/googleicon.png'),
  facebookIcon: require('../assests/images/facebookicon.png'),
  notification: require('../assests/images/notification.png'),
  like: require('../assests/images/like.png'),
  back: require('../assests/images/back.png'),
  chevron: require('../assests/images/chevron.png'),
  no: require('../assests/images/no.png'),
  settings: require('../assests/images/settings.png'),
  demoProfile: require('../assests/images/demoProfile.png'),
  box: require('../assests/images/box.png'),
  tick: require('../assests/images/tick.png'),
  mail: require('../assests/images/mail.png'),
  docProfile: require('../assests/images/docprofile.png'),
  map: require('../assests/images/map.png'),
  handCard: require('../assests/images/handcard.png'),
  upi: require('../assests/images/upi.png'),
};
